CURR_DIR = $(shell pwd)
CC = gcc
CFLAGS = -O3 -g -w
CFLAGS_CHAT = -lpthread
DNS_SOURCE = $(CURR_DIR)/DNS/dnsClient.c
DNS_TARGET = $(CURR_DIR)/DNS/DNS
TCP_CHAT_SERVER_SOURCE = $(CURR_DIR)/TCP_CHAT/tcpChatServer.c
TCP_CHAT_CLIENT_SOURCE = $(CURR_DIR)/TCP_CHAT/tcpChatClient.c
TCP_CHAT_SERVER_TARGET = $(CURR_DIR)/TCP_CHAT/TCPSERVER
TCP_CHAT_CLIENT_TARGTE = $(CURR_DIR)/TCP_CHAT/TCPCLIENT

all:
	$(CC) $(DNS_SOURCE) $(CFLAGS) -o $(DNS_TARGET)
	$(CC) $(TCP_CHAT_SERVER_SOURCE) $(CFLAG) $(CFLAGS_CHAT) -o $(TCP_CHAT_SERVER_TARGET)
	$(CC) $(TCP_CHAT_CLIENT_SOURCE) $(CFLAG) $(CFLAGS_CHAT) -o $(TCP_CHAT_CLIENT_TARGTE)

clean:
	rm $(DNS_TARGET)
	rm $(TCP_CHAT_SERVER_TARGET)
	rm $(TCP_CHAT_CLIENT_TARGTE)
